#pragma once

#include <hal.h>
#include <utils.h>

#define DIGITAL_OUTPUT_GPIO                 HAL_GPIO_D
#define DIGITAL_OUTPUT_PIN_NO0              HAL_GPIO_D_PIN0
#define DIGITAL_OUTPUT_PIN_NO1              HAL_GPIO_D_PIN1
#define DIGITAL_OUTPUT_PIN_SHIFT            0
#define DIGITAL_OUTPUT_PIN_COUNT            2
#define DIGITAL_OUTPUT_PIN_MASK             (1 << DIGITAL_OUTPUT_PIN_NO1) | (1 << DIGITAL_OUTPUT_PIN_NO0)

#define ANALOG_OUTPUT_GPIO                  HAL_GPIO_C
#define ANALOG_OUTPUT_PIN_SHIFT             0
#define ANALOG_OUTPUT_PIN_COUNT             6
#define ANALOG_OUTPUT_PIN_MASK              BIT_MASK (ANALOG_OUTPUT_PIN_SHIFT, ANALOG_OUTPUT_PIN_COUNT)

#define SWITCH_INPUT_GPIO                   HAL_GPIO_D
#define SWITCH_INPUT_GPIO_PIN               HAL_GPIO_D_PIN2
#define SWITCH_INPUT_PIN_MASK               (1 << SWITCH_INPUT_GPIO_PIN)
#define SWITCH_INPUT_INTERRUPT              HAL_Interrupt_External0

#define STATUS_OUTPUT_GPIO                  HAL_GPIO_D
#define STATUS_OUTPUT_PIN_SHIFT             5
#define STATUS_OUTPUT_PIN_COUNT             3
#define STATUS_OUTPUT_PIN_MASK              BIT_MASK (STATUS_OUTPUT_PIN_SHIFT, STATUS_OUTPUT_PIN_COUNT)

#define RUNT_PULSE_TEST_OUTPUT_GPIO         ANALOG_OUTPUT_GPIO
#define RUNT_PULSE_TEST_OUTPUT_PIN_SHIFT    ANALOG_OUTPUT_PIN_SHIFT
#define RUNT_PULSE_TEST_OUTPUT_PIN_COUNT    ANALOG_OUTPUT_PIN_COUNT
#define RUNT_PULSE_TEST_OUTPUT_PIN_MASK     ANALOG_OUTPUT_PIN_MASK

#define TWO_PULSES_TEST_OUTPUT_GPIO         DIGITAL_OUTPUT_GPIO
#define TWO_PULSES_TEST_OUTPUT_PIN_NO0      DIGITAL_OUTPUT_PIN_NO0
#define TWO_PULSES_TEST_OUTPUT_PIN_NO1      DIGITAL_OUTPUT_PIN_NO1
#define TWO_PULSES_TEST_OUTPUT_PIN_SHIFT    DIGITAL_OUTPUT_PIN_SHIFT
#define TWO_PULSES_TEST_OUTPUT_PIN_COUNT    DIGITAL_OUTPUT_PIN_COUNT
#define TWO_PULSES_TEST_OUTPUT_PIN_MASK     DIGITAL_OUTPUT_PIN_MASK
#define TWO_PULSES_TEST_OUTPUT_PIN_NO0_MASK (1 << TWO_PULSES_TEST_OUTPUT_PIN_NO0)
#define TWO_PULSES_TEST_OUTPUT_PIN_NO1_MASK (1 << TWO_PULSES_TEST_OUTPUT_PIN_NO1)

#define SAWTOOTH_TEST_OUTPUT_GPIO           ANALOG_OUTPUT_GPIO
#define SAWTOOTH_TEST_OUTPUT_PIN_SHIFT      ANALOG_OUTPUT_PIN_SHIFT
#define SAWTOOTH_TEST_OUTPUT_PIN_COUNT      ANALOG_OUTPUT_PIN_COUNT
#define SAWTOOTH_TEST_OUTPUT_PIN_MASK       ANALOG_OUTPUT_PIN_MASK

#define TRIANGLE_TEST_OUTPUT_GPIO           ANALOG_OUTPUT_GPIO
#define TRIANGLE_TEST_OUTPUT_PIN_SHIFT      ANALOG_OUTPUT_PIN_SHIFT
#define TRIANGLE_TEST_OUTPUT_PIN_COUNT      ANALOG_OUTPUT_PIN_COUNT
#define TRIANGLE_TEST_OUTPUT_PIN_MASK       ANALOG_OUTPUT_PIN_MASK

#define I2C_TEST_OUTPUT_GPIO                DIGITAL_OUTPUT_GPIO
#define I2C_TEST_OUTPUT_PIN_SHIFT           DIGITAL_OUTPUT_PIN_SHIFT
#define I2C_TEST_OUTPUT_PIN_COUNT           DIGITAL_OUTPUT_PIN_COUNT
#define I2C_TEST_OUTPUT_PIN_MASK            DIGITAL_OUTPUT_PIN_MASK
#define I2C_TEST_OUTPUT_PIN_SCL             DIGITAL_OUTPUT_PIN_NO0
#define I2C_TEST_OUTPUT_PIN_SDA             DIGITAL_OUTPUT_PIN_NO1
#define I2C_TEST_OUTPUT_PIN_SCL_MASK        (1 << I2C_TEST_OUTPUT_PIN_SCL)
#define I2C_TEST_OUTPUT_PIN_SDA_MASK        (1 << I2C_TEST_OUTPUT_PIN_SDA)

#define SINE_TEST_OUTPUT_GPIO               ANALOG_OUTPUT_GPIO
#define SINE_TEST_OUTPUT_PIN_SHIFT          ANALOG_OUTPUT_PIN_SHIFT
#define SINE_TEST_OUTPUT_PIN_COUNT          ANALOG_OUTPUT_PIN_COUNT
#define SINE_TEST_OUTPUT_PIN_MASK           ANALOG_OUTPUT_PIN_MASK

#define DAC_WIDTH_BITS                      6U
#define DAC_WIDTH_MAX_VALUE                 64U

#define HAL_IMPL_USART_BAUD                 10000U
